#!/usr/bin/env python3
"""Generate console assets from the single release management descriptor."""
import json,re
from pathlib import Path
import shutil

root=Path(__file__).resolve().parents[1]
profile=json.loads((root/'config/r17-management.json').read_text())
text=json.dumps(profile,ensure_ascii=False,indent=2)+'\n'
for target in (root/'packaging',root/'console'):
    (target/'management-profile.json').write_text(text)
shutil.copyfile(root/'packaging/management_profile.py',root/'console/management_profile.py')
shutil.copyfile(root/'packaging/release_identity.py',root/'console/release_identity.py')
shutil.copyfile(root/'packaging/voice_preferences.py',root/'console/voice_preferences.py')
# The official daemon still consumes TOML. These are generated deployment
# copies, not additional editable defaults.
path=root/'packaging/robotd-profile.toml'
prefix,policy=path.read_text().split('[policy]\n',1)
section,suffix=policy.split('[safety]',1)
for name,value in profile['defaults']['policy'].items():
    rendered=str(value).lower() if isinstance(value,bool) else str(value)
    line=name+' = '+rendered
    if re.search(r'^'+re.escape(name)+r'\s*=',section,flags=re.M):
        section=re.sub(r'^'+re.escape(name)+r'\s*=.*$',line,section,flags=re.M)
    else:section+=line+'\n'
text=prefix+'[policy]\n'+section+'[safety]'+suffix
path.write_text(text)
(root/'config/robotd-selftrained.toml').write_text('# Generated from config/r17-management.json and packaging/robotd-profile.toml.\n'+text)
js='// Generated by scripts/generate-management-profile.py; edit config/r17-management.json.\n'
js+='const profile='+json.dumps(profile,ensure_ascii=False)+';\n'
js+='export const actionSlots=profile.actions;\n'
js+='const oldBuilds=(first)=>Array.from({length:Math.max(0,23-first)},(_,i)=>`590b986-feetech-ft6-control.${first+i}`).concat(first<=22?["590b986-feetech-ft6-control.14.1"]:[]);\n'
js+='export const modeBuilds=oldBuilds(profile.legacy_first.motion);\nexport const managementBuilds=oldBuilds(profile.legacy_first.management);\n'
js+='export function supportsFeature(report,feature){const explicit=report?.management_capabilities;if(explicit&&Object.hasOwn(explicit,feature))return explicit[feature]===true;const build=String(report?.build||"");if(build.includes("-feetech-ft6-control.")&&!build.startsWith("590b986-"))return profile.features.includes(feature);if(profile.legacy_builds?.[feature])return profile.legacy_builds[feature].some(n=>build===`590b986-feetech-ft6-control.${n}`);return oldBuilds(profile.legacy_first[feature]??100).includes(build);}\n'
(root/'console/static/service-builds.js').write_text(js)
print('Generated console and package management metadata')
