// Real 4K Chromium + real HTTP backend; local fixture checkpoints, no GPU/robot.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {spawn}=require('node:child_process'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
(async()=>{
 const fixture=spawn(process.env.TEST_PYTHON||'python',[path.join(__dirname,'browser_official0151_fixture.py')]);
 fixture.stderr.on('data',b=>process.stderr.write(b));
 const port=await new Promise((resolve,reject)=>{fixture.stdout.on('data',b=>{const m=b.toString().match(/FIXTURE_READY (\d+)/);if(m)resolve(Number(m[1]));});fixture.on('exit',c=>reject(Error('fixture exit '+c)));});
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});
 try{
  const page=await browser.newPage({viewport:{width:3840,height:2160}}),errors=[],posts=[];
  page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message);});
  page.on('request',r=>{if(r.method()==='POST')posts.push({url:r.url(),body:r.postDataJSON()});});
  await page.goto('http://127.0.0.1:'+port);
  await page.locator('#servo-mass-total').waitFor();
  assert.match(await page.locator('#servo-mass-total').innerText(),/820\.00/);
  await page.locator('[data-studio-tab="actuators"]').click();
  const servoText=await page.locator('#robot-table').innerText();
  assert.match(servoText,/电机力矩常数[\s\S]*Torque \/ back-EMF constant/);
  assert.match(servoText,/物理步[\s\S]*15ms/);
  assert.match(servoText,/辨识记录，当前训练未使用/);
  assert.equal(await page.locator('[data-bam][data-key="command_delay"]').count(),0);
  assert.equal(await page.locator('#servo-register-table tbody tr').count(),110);
  await page.fill('#servo-register-search','位置比例增益');
  assert.equal(await page.locator('#servo-register-table tbody tr:visible').count(),1);
  await page.fill('#servo-register-search','');
  await page.locator('[data-bam][data-key="kt"]').click();
  await page.locator('[data-bam-apply][data-key="kt"]').fill('0.7');
  await page.locator('[data-bam-apply][data-key="kt"]').press('Tab');
  await page.waitForFunction(()=>studioDraft.robot.actuator_parameters?.[0]?.kt===.7&&!studioDirty);
  // Restore the fixture's default so the existing teacher contract still matches.
  await page.evaluate(async()=>{delete studioDraft.robot.actuator_parameters;$('robot-overrides').value=pretty(studioDraft.robot);markDirty();await saveStudio();renderStudioTables();});
  await page.evaluate(()=>$('robot-table').scrollTop=0);
  await page.locator('#robot-data').scrollIntoViewIfNeeded();
  await page.screenshot({path:path.join(root,'docs','R1.5.12-servo-4K.png'),fullPage:false});
  await page.locator('[data-studio-tab="servo-mass"]').click();
  const tasks=await page.locator('#task option').evaluateAll(options=>options.map(o=>o.value));
  assert.equal(tasks.length,10);assert(tasks.every(t=>!/-HD1910|-V2/.test(t)));
  assert.equal(await page.locator('#task-backlash').count(),1);
  assert.equal(await page.locator('#task-terrain').count(),1);
  for(const task of tasks){
   await page.selectOption('#task',task);
   await page.waitForFunction(t=>taskReferences.has(t),task);
   assert(await page.locator('#gamma').getAttribute('placeholder'));
  }
  assert.equal(posts.filter(p=>/\/api\/(probe|preflight|describe|setup)$/.test(p.url)).length,0,'task switches must be local');
  await page.evaluate(()=>ensureTaskVisible('Mjlab-VelStand-Rough-Backlash-MicroDuck'));await page.selectOption('#task','Mjlab-VelStand-Rough-Backlash-MicroDuck');
  await page.selectOption('#task-backlash','off');await page.waitForFunction(()=>$('task').value==='Mjlab-VelStand-Rough-MicroDuck');
  await page.selectOption('#task-terrain','Flat');await page.waitForFunction(()=>$('task').value==='Mjlab-VelStand-Flat-MicroDuck');
  assert.equal(await page.locator('#task option').count(),10,'variant changes do not duplicate actions');
  await page.fill('#num-envs','3072');
  assert.equal(await page.locator('#num-envs').inputValue(),'3072');
  assert.equal(await page.locator('#iterations').inputValue(),'8000');
  await page.fill('#num-envs','2048');
  await page.evaluate(()=>window.scrollTo(0,0));
  assert.equal(await page.locator('#iterations').inputValue(),'12000');
  assert.match(await page.locator('#curriculum-rows').innerText(),/1400～1999/);
  assert.match(await page.locator('#curriculum-rows').innerText(),/700～999/);
  await page.fill('#num-envs','1024');
  assert.equal(await page.locator('#iterations').inputValue(),'24000');
  assert.match(await page.locator('#curriculum-rows').innerText(),/2800～3999/);
  await page.fill('#iterations','3333');await page.fill('#num-envs','2048');
  assert.equal(await page.locator('#iterations').inputValue(),'1667');
  await page.fill('#num-envs','1024');
  assert.equal(await page.locator('#iterations').inputValue(),'3333','budget must not compound rounding');
  await page.evaluate(()=>ensureTaskVisible('Mjlab-Velocity-Flat-MicroDuck'));await page.selectOption('#task','Mjlab-Velocity-Flat-MicroDuck');
  assert.equal(await page.locator('#iterations').inputValue(),'200000');
  await page.fill('#num-envs','2048');
  await page.evaluate(()=>ensureTaskVisible('Mjlab-VelStand-Flat-MicroDuck'));await page.selectOption('#task','Mjlab-VelStand-Flat-MicroDuck');
  assert.deepEqual(errors,[]);
  await page.locator('#walk-teacher').waitFor({state:'visible'});
  assert.equal(await page.locator('#walk-teacher option').count(),3);
  assert.equal(await page.locator('#stand-teacher option').count(),3);
  const checkpointLabels=await page.locator('#checkpoint option').allTextContents();
  assert(!checkpointLabels.some(t=>t.includes('历史模型 fixture')));
  assert((await page.locator('#model-table').innerText()).includes('历史模型 fixture'));
  const oldWalk=await page.locator('#walk-teacher option').evaluateAll(options=>options.find(o=>o.text.includes('V2 行走 fixture')).value);
  const oldStand=await page.locator('#stand-teacher option').evaluateAll(options=>options.find(o=>o.text.includes('V2 起身 fixture')).value);
  assert(checkpointLabels.some(t=>t.includes('V2 行走 fixture')&&t.includes('固定摩擦')));
  await page.selectOption('#walk-teacher',oldWalk);await page.selectOption('#stand-teacher',oldStand);
  assert.match(await page.locator('#joint-training-note').innerText(),/原权重.*官方摩擦随机化/);
  await page.selectOption('#checkpoint',oldWalk);
  assert(!(await page.locator('#play-start').isDisabled()));
  await page.locator('#play-start').click();
  await page.waitForFunction(()=>state.jobs.some(j=>j.op==='play'&&j.request.model_source?.origin.engine==='velstand_v2'));
  const evaluation=await page.evaluate(()=>state.jobs.find(j=>j.op==='play'));
  assert.equal(evaluation.request.task,'Mjlab-Velocity-Flat-MicroDuck');
  assert(evaluation.request.repo.endsWith('/official_0151'));
  assert.equal(evaluation.request.model_source.origin.friction_randomization,'fixed');
  assert.equal(posts.filter(p=>/\/api\/(probe|preflight|setup|describe)$/.test(p.url)).length,0);
  // A viewer may remain running while joint training starts.
  await page.locator('#queue-add').click();
  await page.waitForFunction(()=>state.training_queue.entries.length===1);
  await page.locator('#train-start').click();
  await page.waitForFunction(()=>state.jobs.some(j=>j.op==='train'&&j.request.task==='Mjlab-VelStand-Flat-MicroDuck'&&j.status==='starting'));
  const joint=await page.evaluate(()=>state.jobs.find(j=>j.op==='train'&&j.status==='starting'));
  assert.equal(joint.request.joint.walk.source_job,JSON.parse(oldWalk).source_job);
  assert.equal(joint.request.joint.stand.source_job,JSON.parse(oldStand).source_job);
  assert(!joint.request.model_source);
  assert.equal(joint.request.num_envs,2048);
  assert.equal(joint.request.iterations,12000);
  assert.equal(joint.request.sample_alignment_version,1);
  assert.equal(joint.request.save_interval,1000);
  const diagnostic=await page.evaluate(()=>jointDiagnostics({request:{task:'Mjlab-VelStand-Flat-MicroDuck'},metrics:[{expert_bc:.123,expert_bc_fallen_frac:.15,expert_bc_anchor_frac:.65,rewards:{track_linear_velocity:.75,body_ang_vel:-.02}}]}));
  assert.match(diagnostic,/15.0%/);assert.match(diagnostic,/65.0%/);assert.match(diagnostic,/0.123/);
  assert.match(await page.locator('#chart-legend').innerText(),/行走老师覆盖/);
  assert.match(await page.locator('#chart-legend').innerText(),/未上报/);
  assert.equal(posts.filter(p=>/\/api\/train$/.test(p.url)).length,0);
  assert.equal(posts.filter(p=>/\/api\/(probe|preflight|setup|describe)$/.test(p.url)).length,0);
  await page.selectOption('#task','Mjlab-SitStand-Flat-MicroDuck');
  assert.equal(await page.locator('#iterations').inputValue(),'30000');
  assert.match(await page.locator('#task-description').innerText(),/vx=1.*vx=0/);
  await page.evaluate(()=>ensureTaskVisible('Mjlab-Velocity-Flat-MicroDuck'));await page.selectOption('#task','Mjlab-Velocity-Flat-MicroDuck');
  await page.fill('#num-envs','4096');
  assert.equal(await page.locator('#num-envs').inputValue(),'4096');
  assert.equal(await page.locator('#iterations').inputValue(),'50000');
  assert.equal(await page.locator('#learning-rate').inputValue(),'');
  assert(!(await page.locator('#resume option').allTextContents()).some(t=>t.includes('V2 行走 fixture')));
  assert.deepEqual(errors,[]);
  // The active run's course remains pinned to 2048 even if the next page form changes.
  assert.match(await page.locator('#curriculum-rows').innerText(),/1400～1999/);
  await page.evaluate(()=>ensureTaskVisible('Mjlab-VelStand-Flat-MicroDuck'));await page.selectOption('#task','Mjlab-VelStand-Flat-MicroDuck');
  await page.fill('#num-envs','2048');
  await page.screenshot({path:path.join(root,'docs','R1.5.12-joint-4K.png'),fullPage:false});
  console.log('4K UI OK: bilingual BAM/actuator fields, 110 searchable registers, immediate BAM edit, joint metrics, 10 action profiles; 2048/1024 budgets+courses; V2 teachers+joint start; no probes/JS errors');
 }finally{await browser.close();fixture.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exit(1)});
