const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {spawn}=require('node:child_process');
const path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
(async()=>{
 const fixture=spawn(process.env.TEST_PYTHON||'python',[path.join(__dirname,'browser_official0151_fixture.py')]);
 fixture.stderr.on('data',b=>process.stderr.write(b));
 const port=await new Promise((resolve,reject)=>{fixture.stdout.on('data',b=>{const m=b.toString().match(/FIXTURE_READY (\d+)/);if(m)resolve(Number(m[1]));});fixture.on('exit',c=>reject(Error('Fixture exited '+c)));});
 let browser;
 try{
  browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});
  const page=await browser.newPage({viewport:{width:3840,height:2160}}),errors=[],checks=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(r.method()==='POST'&&/\/api\/(probe|preflight|setup)$/.test(r.url()))checks.push(r.url());});
  await page.goto('http://127.0.0.1:'+port);
  await page.waitForFunction(()=>state?.jobs.length>0&&$('task').options.length===10);
  await page.evaluate(()=>ensureTaskVisible('Mjlab-Velocity-Flat-MicroDuck'));
  await page.evaluate(()=>ensureTaskVisible('Mjlab-Velocity-Flat-MicroDuck'));
  await page.selectOption('#task','Mjlab-Velocity-Flat-MicroDuck');
  assert.equal(await page.locator('#training-firmware-p').inputValue(),'3');
  await page.locator('#training-firmware-p').fill('5');await page.locator('#training-firmware-p').press('Tab');
  await page.evaluate(()=>loadState());
  assert.equal(await page.evaluate(()=>readParameters().training_firmware_p),5);
  await page.evaluate(()=>ensureTaskVisible('Mjlab-StandUp-Flat-MicroDuck'));
  await page.selectOption('#task','Mjlab-StandUp-Flat-MicroDuck');
  assert.equal(await page.locator('#training-firmware-p').inputValue(),'5');
  const source=await page.evaluate(()=>[...$('resume').options].find(o=>o.value).value);
  await page.selectOption('#resume',source);
  await page.waitForFunction(()=>$('training-firmware-p').disabled);
  assert.equal(await page.evaluate(()=>currentTrainingFirmwareP()),5);
  await page.selectOption('#resume','');
  await page.evaluate(()=>ensureTaskVisible('Mjlab-Velocity-Flat-MicroDuck'));
  await page.selectOption('#task','Mjlab-Velocity-Flat-MicroDuck');
  await page.locator('#training-firmware-p').fill('2.69');await page.locator('#training-firmware-p').press('Tab');
  assert.match(await page.evaluate(()=>{try{readParameters();return '';}catch(e){return e.message;}}),/整数/);
  await page.locator('#training-firmware-p').fill('3');await page.locator('#training-firmware-p').press('Tab');
  await page.selectOption('#training-action-scale','0.7');
  await page.locator('#queue-add').click();
  await page.waitForFunction(()=>state.training_queue.entries.length===1);
  assert.equal(await page.evaluate(()=>state.training_queue.entries[0].request.training_firmware_p),3);
  await page.locator('#training-firmware-p').fill('5');await page.locator('#training-firmware-p').press('Tab');
  await page.evaluate(()=>loadState());
  assert.equal(await page.evaluate(()=>state.training_queue.entries[0].request.training_firmware_p),3);
  assert.match(await page.locator('#training-summary').innerText(),/P 3/);
  assert(await page.evaluate(()=>{const r=['training-firmware-p','training-action-scale','head-filter-alpha','legs-filter-alpha'].map(id=>$(id).getBoundingClientRect());return r.every(x=>Math.abs(x.top-r[0].top)<1&&x.width>80);}), 'four controls share a row');
  await page.locator('#training-firmware-p').fill('3');await page.locator('#training-firmware-p').press('Tab');
  await page.locator('#parameters').screenshot({path:path.join(root,'docs','R1.5.14-servo-p-4K.png')});
  assert.deepEqual(errors,[]);assert.deepEqual(checks,[]);
  console.log('SERVO_P_OK: editable integer P3/P5; saved resume preserved; queued P frozen; 4K aligned; no probes or JS errors');
 }finally{if(browser)await browser.close();fixture.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
